version: '3'

services:
  mysql:
    build: ./mysql
    ports:
      - "9906:3306"
  laravel:
    build: ./laravel
    depends_on:
      - mysql
    volumes:
      - ./laravel/src:/var/www
    ports:
      - "8080:80"
    command: ["/wait-for-it.sh", "mysql:3306", "--", "/start.sh"]  
